language: python
python:
  - 3.7
  - 3.6
  - 3.5
  - 3.4
  - 2.7

install:
  - pip install tox-travis

script:
  - tox

before_install:
  - pip install codecov

after_success:
  - tox -e coverage-report
  - codecov

notifications:
  email: false
