language: python
matrix:
  fast_finish: true
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: pypy
      env: TOXENV=pypy
    - python: pypy3
      env: TOXENV=pypy3
    - python: "3.7"
      env: TOXENV=py37
      dist: xenial
      sudo: true
    - python: 3.6-dev
      env: TOXENV=py36
    - python: 3.7-dev
      env: TOXENV=py37
    - python: "3.6"
      env: TOXENV=lint
    - python: "3.6"
      env: TOXENV=manifest
    - python: "3.7"
      env: TOXENV=dev-dependencies
      dist: xenial
      sudo: true
    - python: "3.7"
      env: TOXENV=snyk
      dist: xenial
      sudo: true
    - python: "3.7"
      env: TOXENV=coverage-report
      dist: xenial
      sudo: true
  allow_failures:
    - python: 3.6-dev
    - python: 3.7-dev

install: pip install tox
script:
  - tox
notifications:
  email: false
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: cfp2000
  password:
    secure: EUV7/fARxxL+JVJ7GjW1u0P7xUnsiQtY5mLDmnGU1vUFJmhT0OBOwibfcnUk0Sn2fbMpqjW/gQDo37RMPqGNwPjUGqGAuNVrxRRM9hAwxE2a4yeu+uWQjawEzbU1gggT7VA2BrXdmp2aterdygw/x7xJnpukM83ptoAhYYtHxpby6T3wGNpGh+SslN+PA1QEm8xx+NquIMD+F11FdPhrduylxKbUNPsbor2ajsbr+pMJfWITcAyiHqFaqZRrtNVlCTbc36YKpvi477jztYdjbYMlXPXIyr4IxOmjfum3BAbGlJQw0TJBGgHxu/pQs/k1qyAUtsapDGbPKveK7ZVY+PFjD034nwvz+N7L6Omuvfn41grkQ1v6Vt8QDNDRAlD52kveXL3R2qqMJhSSGVOQ54zGsEohl2euqS8DxMV3ZS7VEeScc/zFLssN741Rrfx/KjlARfkAmsG8joHlYXEBVZIEljV3AYLx3Zul5h8RDMhjV5V9Ek5X+8En8uZGPidwWHMYru1k7FpXb6mSgvqQso5K5ouhnrsZuDR4vKdYCBf4RXaq9uIOEpliGVq0dEipUFK6oqpEWasUdZgmSgAFNQ1oQHtsv5m8C3VD2J0Pe4c44Z9b5ywe/RJbfMQ0/B2nSY3A5qLr2OPFcVgDAKJPyQ+KYs7jd18P9t8e+wN5+3Y=
  skip_existing: true
  on:
    tags: true
    repo: cfp2000/git-open
    python: 3.7
    condition: "$TOXENV = dev-dependencies"
env:
  matrix:
    secure: JUxBnBTSfdSnsvqVj30lrFM68idu27AfvFAzS3FUfyU/3hKNe+sWRN9JKQiUT8Kuck6cdZgazKVxH+6Ya7kNcYHynDSAdOLQS85eXWEDOy4d7Ju8Go46m0+smwU6mIPqu7zYHa/HFcQTi6ykIxmkQbV7sosI7wcN8Osd/awzpCZEUAA9R8JglG3l4R2OIiG2ynUOA5KfAd/xGrA6sUnrUg3ztFDSV6xTU8HdDTWnNYNkphmw9RVuAvkl7m8hPSRbHM95nQ7aUaCJJPMVCZ9E7qvohtO7NNoL5u0UNyitX85/SJV/FdHiPW7nxgkJg9rm1sRccUE8n5egTCm2M3BKXl668YdcqhFbrXn1bh9Ik0nm80TL7fsGBvb5Zq+7VxnJRWjQToIAB/RBhIRnfcISi8h9Wx+WTqstu2nuQb99ehm9W8JqzJNLJtNnhtOt87r1dA7CosmG1U4qXud4Wffqr8ccyR06XGIq8G3EkfZbiOanTQysqqFi4x2B4SdqBFpXfBc1sYyJ+f7+2X49f9utV37psEePdUdE8yIcOqlq+XDU4baG5jA25TrGC3fGdhSlcHxyCOzOmYdklNi/tdEDuf+DJG6U9rzRMgq6gc/e42fXdZtzr6+YDYSYH63P4dM7sAAr1mXhhB2JyFU9J0jfrUNPbrrgrfUVdlZWL6UJwH4=
